config/routes.rb
Pxwh::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  resources :ours do
    collection do
      post 'user_create'
      get 'joinus'
      get 'joinus_a'
      get 'joinus_b'
      get 'joinus_c'
      get 'joinus_d'
      get 'joinus_e'
      get 'elite_team'
      get 'journalism'
      get 'daozha'
      get 'news_trends'
      get 'dynamic_announcement'
    end
    member do
      get 'journalism_show'
    end
  end
  resources :daozhas do
    collection do
      get 'chaoyang'
      get 'nanguan'
      get 'luyuan'
      get 'kuancheng'
      get 'erdao'
      get 'shuangyang'
      get 'jingkai'
      get 'gaoxin'
      get 'qichecheng'
      get 'jingyue'
      get 'changchunzhoubian'
    end
  end
  resources :services
  resources :cases do
    collection do
      get 'dangche'
      get 'longjia'
      get 'weixin'
    end
  end
  resources :clients
  resources :contacts
  namespace :admin do
    match '' => 'home#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :daozhas
    resources :job
    resources :accounts do
      collection do
        post 'update_multiple'
      end
    end
    resources :home
    resources :classic_cases
    resources :customers
    resources :journalisms
    resources :resources do
      get 'download'
      collection do
        get 'upload'
        post 'upfile'
        put 'updatefile'
      end
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates :description, :presence => {:message => "企业详细不能为空！"}

  attr_accessor :avatar
  has_attached_file :avatar, :styles => {:zhengchang => "150x51", :thumb => "68x48#", :huoban => "100x34#"}, :default_url => "/images/:style/missing.png",
                    :url => "/case/:id_partition/:style/:filename"
  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg']

  scope :order_ct_desc, lambda { order("created_at DESC") }

  @filepath="public/roll/"
  @previewpath = "previews/"

  # 删除图片
  def self.deletefile(r_id)
    idstr = format("%09d", r_id.to_s)
    one_path = @filepath+idstr[0, 3]+"/"
    two_path = one_path + idstr[3, 3]+"/"
    three_path = two_path + idstr[6, 3]+"/"
    begin
      `rm -rf #{Rails.root+three_path}`
    rescue
      if system "rm -rf #{Rails.root+three_path}"
        return true
      else
        return false
      end
    end
    return true
  end

  #错误提示
  def Customer.message
    @message
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::MainController
  layout 'admin'
  before_action :customers_params, :only => [:create]
  before_filter :get_customers, :only => [:destroy]

  def index
    @customers = Customer.all.order("id desc").page(params[:page]).per(10)
  end

  def new
    @customer = Customer.new
  end

  def create
    if request.post?
      if params[:customer]
        title = params[:customer][:title]
        avatar = params[:customer][:avatar]
        description = params[:customer][:description]
        imagename = avatar.original_filename
        avatar.original_filename = Time.now.strftime("%Y%m%d%h%m%s")<<rand(99999).to_s<<imagename[imagename.length-4, 4]
        if !avatar.blank? && !description.blank? && !title.blank?
          rc = Customer.create(:avatar => avatar, :title => title, :description => description)
          if rc.valid?
          else
            msg = ""
            rc.errors.full_messages.each { |error| msg+= error }
            flash[:error]= msg
            redirect_to :back and return
          end
          redirect_to admin_customers_path and return
        else
          flash[:error_msg]="添加失败，请检查添加项是否有空值！"
          redirect_to :back
        end
      end
    end
  end

  def show
    @customer = Customer.find params[:id]
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @job = Customer.find(params[:id])
    update_category = @job.update_attributes(
        :title => params[:customer][:title],
        :description => params[:customer][:description]
    )
    if update_category
      respond_to do |job|
        job.html {
          redirect_to admin_customers_path and return
        }
      end
    end
  end

  def destroy
    @customer = Customer.find params[:id]
    Customer.deletefile(@customer.id)
    @customer.destroy
    redirect_to admin_customers_path and return
  end

  private
  def get_customers
    @customer = Customer.where(:id => params[:id]).first
  end

  def customers_params
    params.require(:customer).permit(:avatar, :description, :title)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<script>
    <% if !flash[:error_msg].nil? && !flash[:error_msg].blank?%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="<%= admin_home_index_path %>">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_customers_path %>">合作伙伴</a> <span class="divider">/</span>
    </li>
    <li>
      修改合作伙伴
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-content">
      <%= form_for @customer, :url => admin_customer_path, :method => "put", :html => {:id => "verifytitle", :class => "form-horizontal"} do |f| %>
          <legend>修改合作伙伴</legend>
          <%= f.label "企业名称：" %>
          <%= f.text_field :title %>
          <%= f.label "企业详细：" %>
          <%= f.text_area :description, :style => "width:500px;height:150px" %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script>
    $().ready(function () {
        $("#verifytitle").validate({
            rules: {
                "customer[title]": {
                    required: true
                },
                "customer[description]": {
                    required: true
                }
            },
            messages: {
                "customer[title]": {
                    required: "请上填写企业名称"
                },
                "customer[description]": {
                    required: "请填写企业详细"
                }
            }
        });
    });
</script>

app/views/admin/customers/index.html.erb
<div>
  <ul class="breadcrumb">
    <li>
      <a href="<%= admin_home_index_path %>">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_customers_path %>">合作伙伴</a> <span class="divider">/</span>
    </li>
    <li>
      合作伙伴列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 合作伙伴列表</h2>
    </div>
    <div class="box-content">
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>企业名称</th>
          <th>小伙伴logo</th>
          <th>企业详细</th>
          <th>创建时间</th>
          <th>查看</th>
          <th>修改</th>
          <th>删除</th>
        </tr>
        </thead>
        <tbody>
        <div class="form-actions">
          <a class="btn btn-primary" href="<%= new_admin_customer_path %>">
            添加企业
          </a>
        </div>
        <% @customers.each do |roll| %>
            <tr>
              <td><%= roll.id %></td>
              <td><%= roll.title %></td>
              <td><%= image_tag roll.avatar.url(:thumb) %></td>
              <td><%= truncate_u(roll.description, 30) %></td>
              <td class="center"><%= my_datetime_format roll.created_at %></td>
              <td>
                <a class="btn btn-success" href="<%= admin_customer_path(roll) %>">
                  <i class="icon-zoom-in icon-white"></i>
                  查看
                </a>
              </td>
              <td>
                <a class="btn btn-info" href="<%= edit_admin_customer_path(roll) %>">
                  <i class="icon-edit icon-white"></i>
                  修改
                </a>
              </td>
              <td>
                <a class="btn btn-danger" data-confirm="您确定要删除吗?" data-method="delete" href="<%= admin_customer_path(roll.id) %>">
                  <i class="icon-trash icon-white"></i>
                  删除
                </a>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul><%= paginate @customers %></ul>
      </div>
    </div>
  </div>
  <!--/span-->

</div><!--/row-->

app/views/admin/customers/new.html.erb
<script>
    <% if !flash[:error_msg].nil? && !flash[:error_msg].blank?%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="<%= admin_home_index_path %>">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_customers_path %>">合作伙伴</a> <span class="divider">/</span>
    </li>
    <li>
      添加企业伙伴
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-content">
      <div id="content" class="span10" style="padding: 20px">
        <%= form_for @customer, :url => admin_customers_path(@roll), :method => :post, :html => {:id => "roll"} do |f| %>
            <fieldset>
              <legend>添加案例</legend>
              <div class="field">
                <span>企业名称：</span>
                <%= f.text_field :title %>
              </div>
              <br/>

              <div class="field">
                <span>企业LOGO：</span>
                <%= f.file_field :avatar %>
              </div>
              <br/>

              <div class="field">
                <span>企业详细：</span>
                <%= f.text_area :description, :style => "width:500px;height:150px" %>
              </div>
              </br>

              <div class="form-actions">
                <%= f.submit "完成提交", :class => "btn btn-primary" %>
              </div>
            </fieldset>
        <% end %>
        <!--/span-->
      </div>
    </div>
  </div>
</div><!--/row-->
<script src="/admin/js/jquery.validate.js"></script>
<script>
    $().ready(function () {
        $("#roll").validate({
            rules: {
                "customer[title]": {
                    required: true
                },
                "customer[avatar]": {
                    required: true,
                    accept: "jpg|png"
                },
                "customer[description]": {
                    required: true
                }
            },
            messages: {
                "customer[title]": {
                    required: "请上填写企业名称"
                },
                "customer[avatar]": {
                    required: "请上传图片",
                    accept: "图片类型必须是png或jpg"
                },
                "customer[description]": {
                    required: "请填写企业详细"
                }
            }
        });
    });
</script>

app/views/admin/customers/show.html.erb
<script>
    <% if !flash[:error_msg].nil? && !flash[:error_msg].blank?%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="<%= admin_home_index_path %>">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_customers_path %>">合作伙伴</a> <span class="divider">/</span>
    </li>
    <li>
      企业小伙伴
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i>企业小伙伴</h2>
    </div>
    <div class="box-content">
      <div id="content" class="span10" style="padding: 20px">
        <h3><%= @customer.description %></h3><br/><br/>
        <%= image_tag @customer.avatar.url(:zhengchang) %>
        <br/><br/>
        <h3>企业概述：</h3><%= @customer.description %>
        <!--/span-->
      </div>
    </div>
  </div>
</div><!--/row-->
<div class="form-actions">
  <div style="float: right">
    <%= link_to '返回企业管理'.html_safe, admin_customers_path, :class => "btn btn-primary" %>
  </div>
</div>