config/routes.rb
Pxwh::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  resources :ours do
    collection do
      post 'user_create'
      get 'joinus'
      get 'joinus_a'
      get 'joinus_b'
      get 'joinus_c'
      get 'joinus_d'
      get 'joinus_e'
      get 'elite_team'
      get 'journalism'
      get 'daozha'
      get 'news_trends'
      get 'dynamic_announcement'
    end
    member do
      get 'journalism_show'
    end
  end
  resources :daozhas do
    collection do
      get 'chaoyang'
      get 'nanguan'
      get 'luyuan'
      get 'kuancheng'
      get 'erdao'
      get 'shuangyang'
      get 'jingkai'
      get 'gaoxin'
      get 'qichecheng'
      get 'jingyue'
      get 'changchunzhoubian'
    end
  end
  resources :services
  resources :cases do
    collection do
      get 'dangche'
      get 'longjia'
      get 'weixin'
    end
  end
  resources :clients
  resources :contacts
  namespace :admin do
    match '' => 'home#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :daozhas
    resources :job
    resources :accounts do
      collection do
        post 'update_multiple'
      end
    end
    resources :home
    resources :classic_cases
    resources :customers
    resources :journalisms
    resources :resources do
      get 'download'
      collection do
        get 'upload'
        post 'upfile'
        put 'updatefile'
      end
    end
  end

end

app/views/admin/resources/index.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      仓库列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 仓库列表</h2>
    </div>
    <div class="box-content">
      <div class="form-actions">
        <div style="float: left">
          <%= link_to '上传', upload_admin_resources_path, :class => "btn btn-primary" %>
        </div>
      </div>
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>标题</th>
          <th>内容</th>
          <th>创建时间</th>
          <th>下载</th>
          <th>删除</th>
        </tr>
        </thead>
        <tbody>
        <% @res.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= q.title %></td>
              <td><%= q.description %></td>
              <td class="center"><%= my_datetime_format q.created_at %></td>
              <td class="center"><%= link_to "下载",admin_resource_download_path(q) %></td>
              <td><%= link_to '删除', admin_resource_path(q), :method => :delete, :confirm => "您确定要删除吗?" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @res %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/resources/upload.html.erb
<link href="/admin/css/validate-xx.css" rel="stylesheet"/>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="#">上传</a> <span class="divider">/</span>
    </li>
  </ul>
</div>

<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-edit"> </i> 上传资源</h2>
    </div>
    <div class="box-content">
      <%= form_for @resource, :url => upfile_admin_resources_path, :method => "post", :html => {:class => "form-horizontal"} do |f| %>
          <fieldset>
            <legend>上传资源</legend>
            <div class="control-group">
              <label class="control-label" for="typeahead">名称 </label>

              <div class="valiTitlrControlBox">
                <%= f.text_field :title, :class => "valiTitle" %>
                <p class="help-block">字数有效范围1~20</p>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="textarea2">简介</label>

              <div class="valiIntroControlBox">
                <%= f.text_area :description, :class => "cleditor", :style => "width:465px", :rows => 5 %>
                <p class="help-block">字数有效范围1~200</p>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="fileInput">下载文件</label>

              <div class="valiImgControlBox">
                <%= f.file_field :down, :class => "input-file uniform_on" %>
                <p class="help-block">提供下载文件，格式必须是excel</p>
              </div>
            </div>
            <div class="form-actions">
              <input type="submit" value="上传文件" onclick="this.value='上传中，请稍候...'" class="btn btn-primary"/>
            </div>
          </fieldset>
      <% end %>
    </div>
  </div>
</div>
<script>
    $().ready(
            function () {
                $("#new_resource").validate({
                    rules: {
                        "resource[title]": {
                            required: true,
                            maxlength: 20
                        },
                        "resource[description]": {
                            required: true,
                            maxlength: 200
                        },
                        "resource[down]": {
                            required: true
                        }
                    },
                    messages: {
                        "resource[title]": {
                            required: "标题为必填项",
                            maxlength: "最大长度为20"
                        },
                        "resource[description]": {
                            required: "简介为必填项",
                            maxlength: "最大长度为200"
                        },
                        "resource[down]": {
                            required: "请选择文件！"
                        }
                    },
                    errorClass: "error",
                    highlight: function (element, errorClass) {
                        $(element).parent().parent().addClass(errorClass);
                    },
                    unhighlight: function (element, errorClass) {
                        $(element).parent().parent().removeClass(errorClass);
                    },
                    errorPlacement: function (error, element) {
                        error.appendTo(element.parent());
                    },
                    errorElement: "span"
                })
            });
    <% if !flash[:error_msg].nil? && !flash[:error_msg].blank? %>
    alert('<%=flash[:error_msg]%>');
    <% end %>
</script>