config/routes.rb
Pxwh::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  resources :ours do
    collection do
      post 'user_create'
      get 'joinus'
      get 'joinus_a'
      get 'joinus_b'
      get 'joinus_c'
      get 'joinus_d'
      get 'joinus_e'
      get 'elite_team'
      get 'journalism'
      get 'daozha'
      get 'news_trends'
      get 'dynamic_announcement'
    end
    member do
      get 'journalism_show'
    end
  end
  resources :daozhas do
    collection do
      get 'chaoyang'
      get 'nanguan'
      get 'luyuan'
      get 'kuancheng'
      get 'erdao'
      get 'shuangyang'
      get 'jingkai'
      get 'gaoxin'
      get 'qichecheng'
      get 'jingyue'
      get 'changchunzhoubian'
    end
  end
  resources :services
  resources :cases do
    collection do
      get 'dangche'
      get 'longjia'
      get 'weixin'
    end
  end
  resources :clients
  resources :contacts
  namespace :admin do
    match '' => 'home#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :daozhas
    resources :job
    resources :accounts do
      collection do
        post 'update_multiple'
      end
    end
    resources :home
    resources :classic_cases
    resources :customers
    resources :journalisms
    resources :resources do
      get 'download'
      collection do
        get 'upload'
        post 'upfile'
        put 'updatefile'
      end
    end
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写招聘职位"}, :length => {:maximum => 25, :message => "职位必须小于25个字"}
  validates :description, :presence => {:message => "请填写招聘信息"}
  scope :order_ct_desc, lambda { order("created_at DESC") }

  QUESTION_CATEGORYS = [["请选择", 0],["高管", 1], ["网络", 2], ["销售", 3], ["行政", 4], ["工程", 5]]

  def Job.question_category_name(category_id)
    QUESTION_CATEGORYS.each do |item|
      return item[0] if item[1] == category_id
    end
  end

  def question_category_name
    Job.question_category_name(self.question_category_id)
  end
end

app/controllers/admin/job_controller.rb
class Admin::JobController < Admin::MainController
  layout 'admin'

  def index
    @jobs = Job.order_ct_desc.page(params[:page]).per(10)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(
        :title => params[:job][:title],
        :description => params[:job][:description],
        :question_category_id => params[:job][:question_category_id]
    )
    if @job.save
      flash[:note] = "创建成功"
      redirect_to admin_job_index_path and return
    else
      flash[:error_msg] = @job.errors.values.join(";    ")
      redirect_to :back and return
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    update_category = @job.update_attributes(
        :title => params[:job][:title],
        :description => params[:job][:description],
        :question_category_id => params[:job][:question_category_id]
    )
    if update_category
      respond_to do |job|
        job.html {
          redirect_to admin_job_index_path and return
        }
      end
    end
  end

  def show
    @job = Job.find params[:id]
  end

  #   删除
  def destroy
    @job = Job.find(params[:id])
    flash[:error_msg] = @job.destroy ? "删除成功" : "请稍后再试"
    redirect_to admin_job_index_path and return
  end
end

app/views/admin/job/edit.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_job_index_path %>">招聘管理</a> <span class="divider">/</span>
    </li>
    <li>
      信息修改
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 信息修改</h2>
    </div>
    <div class="box-content">
      <%= form_for @job, :url => admin_job_path, :method => "put", :html => {:id => "verifytitle", :class => "form-horizontal"} do |f| %>
          <legend>信息修改</legend>
          <%= f.label "招聘职位：" %>
          <%= f.text_field :title %>
          <%= f.label "职位分类：" %>
          <%= f.select :question_category_id, options_for_select(Job::QUESTION_CATEGORYS) %>
          <%= f.label "任职资格：" %>
          <%= f.cktext_area :description %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script>
    $().ready(function () {
        $("#verifytitle").validate({
            rules: {
                "job[title]": {
                    required: true
                },
                "job[description]": {
                    required: true
                }
            },
            messages: {
                "job[title]": {
                    required: "招聘职位不能为空"
                },
                "job[description]": {
                    required: "任职资格不能为空"
                }
            }
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/job/index.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      招聘信息列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 招聘信息列表</h2>
    </div>
    <div class="box-content">
      <div class="form-actions">
        <div style="float: left">
          <%= link_to '添加招聘信息', new_admin_job_path, :class => "btn btn-primary" %>
        </div>
      </div>
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>招聘职位</th>
          <th>招聘类型</th>
          <th>创建时间</th>
          <th>详细</th>
          <th>修改</th>
          <th>删除</th>
        </tr>
        </thead>
        <tbody>
        <% @jobs.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= q.title %></td>
              <td><%= q.question_category_name %></td>
              <td class="center"><%= my_datetime_format q.created_at %></td>
              <td class="center"><%= link_to "详细", admin_job_path(q) %></td>
              <td><%= link_to '修改', edit_admin_job_path(q) %></td>
              <td><%= link_to '删除', admin_job_path(q), :method => :delete, :confirm => "您确定要删除吗?" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @jobs %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/job/new.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_job_index_path %>">招聘管理</a> <span class="divider">/</span>
    </li>
    <li>
      添加招聘信息
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 添加招聘信息</h2>
    </div>
    <div class="box-content">
      <%= form_for(:job, :url => admin_job_index_path, :id => "verifytitle", :class => "form-horizontal") do |f| %>
          <legend>添加招聘信息</legend>
          <%= f.label "招聘职位：" %>
          <%= f.text_field :title %>
          <%= f.label "职位分类：" %>
          <%= f.select :question_category_id, options_for_select(Job::QUESTION_CATEGORYS) %>
          <%= f.label "任职资格：" %>
          <%= f.cktext_area :description %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">发布信息</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script>
    $().ready(function () {
        $("#verifytitle").validate({
            rules: {
                "job[title]": {
                    required: true
                },
                "job[description]": {
                    required: true
                }
            },
            messages: {
                "job[title]": {
                    required: "招聘职位不能为空"
                },
                "job[description]": {
                    required: "任职资格不能为空"
                }
            }
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/job/show.html.erb
<div>
  <ul class="breadcrumb">
    <li>
      <a href=#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_job_index_path %>">招聘管理</a> <span class="divider">/</span>
    </li>
    <li>
      招聘内容
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-content">
      <p>
        招聘职位：<%= @job.title %>
      </p><br/>

      <p>
        任职资格：<%= @job.description.html_safe %>
      </p>
      <br/><br/>

      <div style="float: left">
        <%= link_to '返回招聘列表', admin_job_index_path, :class => "btn btn-primary" %>
      </div>
      <br/><br/>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->