config/routes.rb
Pxwh::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  resources :ours do
    collection do
      post 'user_create'
      get 'joinus'
      get 'joinus_a'
      get 'joinus_b'
      get 'joinus_c'
      get 'joinus_d'
      get 'joinus_e'
      get 'elite_team'
      get 'journalism'
      get 'daozha'
      get 'news_trends'
      get 'dynamic_announcement'
    end
    member do
      get 'journalism_show'
    end
  end
  resources :daozhas do
    collection do
      get 'chaoyang'
      get 'nanguan'
      get 'luyuan'
      get 'kuancheng'
      get 'erdao'
      get 'shuangyang'
      get 'jingkai'
      get 'gaoxin'
      get 'qichecheng'
      get 'jingyue'
      get 'changchunzhoubian'
    end
  end
  resources :services
  resources :cases do
    collection do
      get 'dangche'
      get 'longjia'
      get 'weixin'
    end
  end
  resources :clients
  resources :contacts
  namespace :admin do
    match '' => 'home#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :daozhas
    resources :job
    resources :accounts do
      collection do
        post 'update_multiple'
      end
    end
    resources :home
    resources :classic_cases
    resources :customers
    resources :journalisms
    resources :resources do
      get 'download'
      collection do
        get 'upload'
        post 'upfile'
        put 'updatefile'
      end
    end
  end

end

app/views/common/_casedh.html.erb
<div id="sidebar">
  <div id="sidebar_menu" class="yahei">
    <h3><span class="font_20 black block">case</span><span class="font_14 black block">经典案例</span></h3>
    <ul>
      <li id="sidebar_menu01"><a href="http://www.ccpxcm.com/cases">经典案例</a></li>
    </ul>

    <ul>
      <li id="sidebar_menu02"><a href="http://www.ccpxcm.com/cases/dangche">档车杆</a></li>
    </ul>

    <ul>
      <li id="sidebar_menu03"><a href="http://www.ccpxcm.com/cases/longjia">机场LED</a></li>
    </ul>

    <ul>
      <li id="sidebar_menu04"><a href="http://www.ccpxcm.com/cases/weixin">微官网</a></li>
    </ul>
  </div>

  <p id="sidebar_tel">
    <a target="_blank" href="http://www.ccpxcm.com/cases">
      <img src="/images/matrix_tel.gif" alt="朋兴传媒"/>
    </a>
  </p>
</div>

app/views/common/_daozhadh.html.erb
<link type="text/css" rel="stylesheet" href="../stylesheets/base.css" media="all">
<link rel="stylesheet" type="text/css" href="../stylesheets/list-fang.css" media="all">
<div id="ad_d22" style="height: 50px;">
  <a href="http://www.ccpxcm.com/services" target="_blank">
    <img src="../images/pxhf.jpg">
  </a>
</div>
<section id="selection">
  <div class="relative">
    <dl class="secitem" id="filter_quyu">
      <dt>区域：</dt>
      <dd>
        <a href="<%= daozhas_path %>">全部</a>
        <a href="<%= chaoyang_daozhas_path %>">朝阳</a>
        <a href="<%= nanguan_daozhas_path %>">南关</a>
        <a href="<%= luyuan_daozhas_path %>">绿园</a>
        <a href="<%= kuancheng_daozhas_path %>">宽城</a>
        <a href="<%= erdao_daozhas_path %>">二道</a>
        <a href="<%= shuangyang_daozhas_path %>">双阳</a>
        <a href="<%= jingkai_daozhas_path %>">经开</a>
        <a href="<%= gaoxin_daozhas_path %>">高新</a>
        <a href="<%= qichecheng_daozhas_path %>">汽车城</a>
        <a href="<%= jingyue_daozhas_path %>">净月</a>
        <a href="<%= changchunzhoubian_daozhas_path %>">长春周边</a>
      </dd>
    </dl>
  </div>
</section>

app/views/common/_footer.html.erb
<script type="text/javascript" src="/javascripts/colortip-1.0-jquery.js"></script>
<script>$(document).ready(function () {

    $('[title]').colorTip({color: 'yellow'});

});</script>
<div id="footer" class="yahei">
  <div id="bottom">
    <p id="copyright" class="black">Copyright &copy; 2009-2014 PengXing Culture Spread. All Rights Reserved.　　
      版权所有：
      <a href="<%= root_path %>" target="_blank" alt="长春朋兴文化传媒有限公司" class="red">
        长春朋兴文化传媒有限公司
      </a>　
      <!-- 分享 -->　
      <script>window._bd_share_config = {"common": {"bdSnsKey": {}, "bdText": "", "bdMini": "2", "bdPic": "", "bdStyle": "0", "bdSize": "16"}, "share": {}, "image": {"viewList": ["qzone", "tsina", "tqq", "renren", "weixin"], "viewText": "分享到：", "viewSize": "16"}, "selectShare": {"bdContainerClass": null, "bdSelectMiniList": ["qzone", "tsina", "tqq", "renren", "weixin"]}};
      with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
      <!-- end -->
      <!--备案序号：<a href="http://www.miibeian.gov.cn" target="_blank">鄂ICP备0xxxxxxxx号</a>-->

        <iframe id=review height=20 marginheight=0 src="http://follow.v.t.qq.com/index.php?c=follow&a=quick&appkey=801505785&sign=eb716d74&v=2&name=pengxingchuanmei&style=6&t=1399961028333&f=1" frameborder=0 width=50 allowtransparency marginwidth=0></iframe>

      <a href="msnim:chat?contact=admin@ccpxcm.com">
        <img src="/images/Offline.gif?mkt=zh-cn" align="absbottom"/>admin@ccpxcm.com
      </a>
      <a href="msnim:chat?contact=admin@ccpxcm.com">
        <img src="/images/Offline.gif?mkt=zh-cn" align="absbottom"/>bug@ccpxcm.com
      </a>
    </p>
  </div>
</div>

app/views/common/_jobdh.html.erb
<div class="sort">
  <div class="solid_line">
  </div>
  <h4 class="font_12 coffee">
    招聘分类
  </h4>
  <ul>
    <li><a id="hl1_st4" href="http://www.ccpxcm.com/ours/joinus_a">高管</a></li>
    <li><a id="hl1_st3" href="http://www.ccpxcm.com/ours/joinus_b">网络</a></li>
    <li><a id="hl1_st2" href="http://www.ccpxcm.com/ours/joinus_c">销售</a></li>
    <li><a id="hl1_st4" href="http://www.ccpxcm.com/ours/joinus_d">行政</a></li>
    <li><a id="hl1_st4" href="http://www.ccpxcm.com/ours/joinus_e">工程</a></li>
  </ul>
  <div class="clear"></div>
  <div class="solid_line"></div>
</div>
<div class="clear">
</div>

app/views/common/_kefu.html.erb
<!-- 客服 -->
<div class="serviceleft">
  <div class="si_serviceleft">
    <div class="si_serviceleft2" style="display: block;">
      <ul>
        <li class="si_serviceleftLI1" style="">
          <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=208263915&site=qq&menu=yes">
            朋兴客服
          </a>
        </li>
        <li class="si_serviceleftLI1" style="">
          <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2544481839&site=qq&menu=yes">
            朋兴客服
          </a>
        </li>
        <li class="si_serviceleftLI2" style="">
          <div style="display: none;"><img src="/images/weixin/wx2wm.png" alt="朋兴传媒微信"></div>
        </li>
      </ul>
    </div>
  </div>
</div>
<script>
    $(function () {
        $(".si_serviceleftLast").hover(function () {
            $(".si_serviceleftLast div").fadeIn(0);
        }, function () {
            $(".si_serviceleftLast div").fadeOut(0);
        })
        $(".si_serviceleftLI2").hover(function () {
            $(".si_serviceleftLI2 div").fadeIn(0);
        }, function () {
            $(".si_serviceleftLI2 div").fadeOut(0);
        })
        $(".si_serviceleft2 ul li").hover(function () {
            $(this).css('background-color', '#d93d69');
        }, function () {
            $(this).css('background-color', '');
        })
    })
</script>

<!-- 右侧分享 -->
<script type="text/javascript" src="http://s.shareto.com.cn/js/shareto_float.js#color=4&align=left&move=1" charset="utf-8"></script>
<!-- 右侧分享END -->

app/views/common/_menuour.html.erb
<div id="sidebar">
  <div id="sidebar_menu" class="yahei">
    <h3>
      <span class="font_20 black block">our</span>
      <span class="font_14 black block">关于我们</span>
    </h3>
    <ul>
      <li id="sidebar_menu01"><a href="http://www.ccpxcm.com/ours">我们是谁</a></li>
      <li id="sidebar_menu03"><a href="http://www.ccpxcm.com/ours/elite_team">精英团队</a></li>
      <li id="sidebar_menu04"><a href="http://www.ccpxcm.com/ours/joinus">招聘信息</a></li>
      <li id="sidebar_menu05"><a href="http://www.ccpxcm.com/ours/journalism">热点新闻</a></li>
      <li id="sidebar_menu06"><a href="http://www.ccpxcm.com/ours/daozha">道闸点位</a></li>
    </ul>
  </div>
  <p id="sidebar_tel">
    <a target="_blank" href="http://www.ccpxcm.com/ours">
      <img src="/images/matrix_tel.gif" alt="朋兴传媒"/>
    </a>
  </p>
</div>
<%= render 'common/kefu' %>

app/views/common/_navigation.html.erb
<!-- 导航 -->
<script>
    function uaredirect(murl) {
        try {
            if (document.getElementById("bdmark") != null) {
                return;
            }
            var urlhash = window.location.hash;
            if (!urlhash.match("fromapp")) {
                if ((navigator.userAgent.match(/(iPhone|iPod|Android|ios|iPad)/i))) {
                    location.replace(murl);
                }
            }
        } catch (err) {
        }
    }
    uaredirect("http://m.ccpxcm.com/");
</script>
<div id="head" class="clearfix">
  <div id="top">
    <h1 id="logo">
      <a href="/" title="朋兴传媒">
        <span>[长春朋兴文化传媒有限公司]</span>
      </a>
    </h1>

    <div id="menu">
      <ul>
        <li id="menu_home"><a href="http://www.ccpxcm.com/"><span>首页</span></a></li>
        <li id="menu_our"><a href="http://www.ccpxcm.com/ours"><span>关于我们</span></a></li>
        <li id="menu_services"><a href="http://www.ccpxcm.com/services"><span>互动服务</span></a></li>
        <li id="menu_case"><a href="http://www.ccpxcm.com/cases"><span>经典案例</span></a></li>
        <li id="menu_client"><a href="http://www.ccpxcm.com/clients"><span>合作客户</span></a></li>
        <li id="menu_contact"><a href="http://www.ccpxcm.com/contacts"><span>联系我们</span></a></li>
      </ul>
    </div>
  </div>
</div>

<!--                     开始        ------------------>
<div id="search_bg">
  <div id="search_bar">
    <div id="newcase">
      <div class="newcase_texts">
        <!--首页最新案例:开始-->
        <div id="newcase_text1" style="display: block">
          <span class="yahei black b">公司告示：</span>
          <img style="-webkit-user-select: none;" src="http://www.uusucai.com/d/file/wangye/wangyetubiao/2013/04/13/b2df5f3f960f132d1401c0263f64d7de.gif" width="16" height="10">

          <% @category_2_journalism.each do |c| %>
              <a href="<%= journalism_show_our_path(c) %>" target="_blank"><%= c.title %></a>
          <% end %>
        </div>
        <!--首页最新案例:结束-->
      </div>
    </div>
    <div id="search_box">
            <span class="yahei black">
              <a href="http://www.ccpxcm.com/ours/journalism">新闻</a> /
              <a href="<%= daozhas_path %>">道闸点位</a> /
              <a href="http://www.ccpxcm.com/ours/joinus">招聘</a> /
              <a href="http://m.ccpxcm.com" target="_blank">WAP</a>
            </span>
    </div>
  </div>
</div>
<!--                     开始end        ------------------>

app/views/common/_sscase.html.erb
<div class="sort">
  <div class="solid_line">
  </div>
  <h4 class="font_12 coffee">
    按类型分类
  </h4>
  <ul>
    <li><a id="hl1_st2" href="http://www.ccpxcm.com/cases/dangche">档车杆</a></li>
    <li><a id="hl1_st3" href="http://www.ccpxcm.com/cases/longjia">机场LED</a></li>
    <li><a id="hl1_st4" href="http://www.ccpxcm.com/cases/weixin">微观网</a></li>
  </ul>
  <div class="clear"></div>
  <div class="solid_line"></div>
</div>
<div class="clear">
</div>